# Generated by Django 4.2.4 on 2023-10-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0002_alter_mypassword_encryption_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypassword',
            name='encryption_key',
            field=models.CharField(max_length=50),
        ),
    ]
